name: meson build

on:
  push:
    branches: 
      - master
    paths:
      - "**.c"
      - "**.cpp"
      - "**.h"
      - ".github/workflows/build.yml"
      - "**meson.build"

jobs:

  tag:
    name: Create release
    runs-on: ubuntu-20.04
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Increment Tag
      id: inc_tag
      uses: mathieudutour/github-tag-action@v5.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate Changelog
      id: changelog
      run: |
        changelog=$(git log ${{ steps.inc_tag.outputs.previous_tag }}..HEAD --no-merges --format="%h %s%+b")
        changelog="${changelog//'%'/'%25'}"
        changelog="${changelog//$'\n'/'%0A'}"
        changelog="${changelog//$'\r'/'%0D'}"
        echo $changelog
        echo "::set-output name=changelog::$changelog"

    - name: Create release
      id: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.inc_tag.outputs.new_tag }}
        release_name: Release ${{ steps.inc_tag.outputs.new_version }}
        body: ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false

  linux:
    name: Build on Linux
    runs-on: ubuntu-20.04
    needs: tag
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install meson and ninja
      run: pip install meson ninja

    - name: Meson setup
      run: meson setup builddir/
      env:
        CC: gcc

    - name: Meson compile
      run: meson compile -C builddir/ -v
      env:
        CC: gcc

    - name: Release add build
      id: release_build
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.tag.outputs.upload_url }}
        asset_path: ./builddir/src/hex-to-image
        asset_name: hex-to-image-linux
        asset_content_type: application/x-sharedlib

  linux_arm64:
    name: Build on Linux(ARM64)
    runs-on: [self-hosted, linux, ARM64]
    needs: tag
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install pip
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip cmake
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install meson and ninja
      run: |
        pip3 install scikit-build
        pip3 install meson ninja

    - name: Meson setup
      run: meson setup builddir/
      env:
        CC: gcc

    - name: Meson compile
      run: meson compile -C builddir/ -v
      env:
        CC: gcc

    - name: Release add build
      id: release_build
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.tag.outputs.upload_url }}
        asset_path: ./builddir/src/hex-to-image
        asset_name: hex-to-image-linux-arm64
        asset_content_type: application/x-sharedlib

  macos:
    name: Build on MacOS
    runs-on: macos-latest
    needs: tag
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install gcc
      run: brew install gcc

    - name: Install meson and ninja
      run: pip install meson ninja

    - name: Meson setup
      run: meson setup builddir/ -Ddynamic=true
      env:
        CC: gcc

    - name: Meson compile
      run: meson compile -C builddir/ -v
      env:
        CC: gcc

    - name: Release add build
      id: release_build
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.tag.outputs.upload_url }}
        asset_path: ./builddir/src/hex-to-image
        asset_name: hex-to-image-macos
        asset_content_type: application/x-sharedlib

  windows:
    name: Build on Windows
    runs-on: windows-latest
    needs: tag
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install meson and ninja
      run: pip install meson ninja

    - name: Meson setup
      run: meson setup builddir/
      env:
        CC: gcc

    - name: Meson compile
      run: meson compile -C builddir/ -v
      env:
        CC: gcc

    - name: Release add build
      id: release_build
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.tag.outputs.upload_url }}
        asset_path: ./builddir/src/hex-to-image.exe
        asset_name: hex-to-image-windows.exe
        asset_content_type: application/vnd.microsoft.portable-executable
