name: meson build

on:
  push:
    branches: 
      - master
    paths:
      - "**.c"
      - "**.cpp"
      - "**.h"
      - ".github/workflows/build.yml"
      - "**meson.build"
      - "meson_options.txt"

jobs:

  tag:
    name: Create release
    runs-on: ubuntu-20.04
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Increment Tag
      id: inc_tag
      uses: mathieudutour/github-tag-action@v5.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate Changelog
      id: changelog
      run: |
        changelog=$(git log ${{ steps.inc_tag.outputs.previous_tag }}..HEAD --no-merges --format="%h %s%+b")
        changelog="${changelog//'%'/'%25'}"
        changelog="${changelog//$'\n'/'%0A'}"
        changelog="${changelog//$'\r'/'%0D'}"
        echo $changelog
        echo "::set-output name=changelog::$changelog"

    - name: Create release
      id: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
      with:
        tag_name: ${{ steps.inc_tag.outputs.new_tag }}
        release_name: Release ${{ steps.inc_tag.outputs.new_version }}
        body: ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            name: linux
          - os: windows-latest
            name: windows
          - os: macos-latest
            name: macos

    name: Build on ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    needs: tag

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install gcc
      id: gcc_install
      if: ${{ matrix.os == 'macos-latest' }}
      run: brew install gcc

    - name: Install meson and ninja
      run: pip install meson ninja

    - name: Meson setup(${{ matrix.name }})
      id: meson_setup
      if: ${{ matrix.os != 'macos-latest' }}
      run: meson setup builddir/
      env:
        CC: gcc

    - name: Meson setup(${{ matrix.name }})
      id: meson_macos_setup
      if: ${{ matrix.os == 'macos-latest' }}
      run: meson setup builddir/ -Ddynamic=true
      env:
        CC: gcc

    - name: Meson compile
      run: meson compile -C builddir/ -v
      env:
        CC: gcc

    - name: Release add build(${{ matrix.name }}
      id: release_build
      if: ${{ matrix.os != 'windows-latest' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.tag.outputs.upload_url }}
        asset_path: ./builddir/src/hex-to-image
        asset_name: hex-to-image-${{ matrix.name }}
        asset_content_type: application/x-sharedlib

    - name: Release add build(${{ matrix.name }}
      id: release_windows_build
      if: ${{ matrix.os == 'windows-latest' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.tag.outputs.upload_url }}
        asset_path: ./builddir/src/hex-to-image.exe
        asset_name: hex-to-image-windows.exe
        asset_content_type: application/vnd.microsoft.portable-executable

  build_linux_arm64:
    name: Build on linux-arm64
    runs-on: [self-hosted, linux, ARM64]
    needs: tag

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install cmake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install meson and ninja
      run: |
        pip install scikit-build
        pip install meson ninja

    - name: Meson setup(linux-arm64)
      id: meson_setup
      run: meson setup builddir/
      env:
        CC: gcc

    - name: Meson compile
      run: meson compile -C builddir/ -v
      env:
        CC: gcc

    - name: Release add build(linux-arm64)
      id: release_build
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.tag.outputs.upload_url }}
        asset_path: ./builddir/src/hex-to-image
        asset_name: hex-to-image-linux-arm64
        asset_content_type: application/x-sharedlib
