# Builds this project on various systems and releases the builds.
# Creates builds for the windows, linux, and macos on x86, as well as a linux arm64 build.
name: meson build

on:
  push:
    branches: 
      - master
    paths:
      - "**.c"
      - "**.cpp"
      - "**.h"
      - ".github/workflows/build.yml"
      - "**meson.build"
      - "meson_options.txt"

jobs:

  tag:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Increment Tag
      id: inc_tag
      uses: mathieudutour/github-tag-action@v5.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate Changelog
      id: changelog
      run: |
        changelog=$(git log ${{ steps.inc_tag.outputs.previous_tag }}..HEAD --no-merges --format="%h %s%+b")
        changelog="${changelog//'%'/'%25'}"
        changelog="${changelog//$'\n'/'%0A'}"
        changelog="${changelog//$'\r'/'%0D'}"
        echo $changelog
        echo "::set-output name=changelog::$changelog"

    - name: Create release
      id: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
      with:
        tag_name: ${{ steps.inc_tag.outputs.new_tag }}
        release_name: Release ${{ steps.inc_tag.outputs.new_version }}
        body: ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            os-name: linux
            pip-path: ~/.cache/pip
          - os: windows-latest
            os-name: windows
            pip-path: ~\AppData\Local\pip\Cache
          - os: macos-latest
            os-name: macos
            pip-path: ~/Library/Caches/pip
          - os: ARM64 # self-hosted linux ARM64 runners
            os-name: linux-arm64
            pip-path: ~/.cache/pip

    name: Build and release on ${{ matrix.os-name }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Python
      if: ${{ matrix.os-name != 'linux-arm64' }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Cache pip packages
      id: pip_cache
      uses: actions/cache@v2
      with:
        path: ${{ matrix.pip-path }}
        key: ${{ matrix.os-name }}-pip

    - name: Install gcc(macos)
      id: gcc_install
      if: ${{ matrix.os-name == 'macos' }}
      run: brew install gcc
  
    - name: Install cmake(linux-arm64)
      id: cmake_install
      if: ${{ matrix.os-name == 'linux-arm64' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Install meson and ninja
      id: meson_install
      run: pip install scikit-build ninja meson

    - name: Meson setup(${{ matrix.os-name }})
      id: meson_setup
      if: ${{ matrix.os-name != 'macos' }}
      run: meson setup builddir/
      env:
        CC: gcc

    - name: Meson setup(macos)
      id: meson_macos_setup
      if: ${{ matrix.os-name == 'macos' }}
      run: meson setup builddir/ -Ddynamic=true
      env:
        CC: gcc

    - name: Meson compile
      run: meson compile -C builddir/ -v

    - name: Release add build(${{ matrix.os-name }}
      id: release_build
      if: ${{ matrix.os != 'windows-latest' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.tag.outputs.upload_url }}
        asset_path: ./builddir/src/hex-to-image
        asset_name: hex-to-image-${{ matrix.os-name }}
        asset_content_type: application/x-sharedlib

    - name: Release add build(${{ matrix.os-name }}
      id: release_windows_build
      if: ${{ matrix.os == 'windows-latest' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.tag.outputs.upload_url }}
        asset_path: ./builddir/src/hex-to-image.exe
        asset_name: hex-to-image-windows.exe
        asset_content_type: application/vnd.microsoft.portable-executable
