# Tests whether the source code can be built with meson compile.
# Compiles the source code and runs unit tests.
# All tests are run on windows, ubuntu, macos, and linux-arm64.
name: meson test

on:
  push:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.h"
      - ".github/workflows/test.yml"
      - "**meson.build"
      - "meson_options.txt"
  pull_request:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.h"
      - ".github/workflows/test.yml"
      - "**meson.build"
      - "meson_options.txt"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            os-name: linux
            pip-path: ~/.cache/pip
          - os: windows-latest
            os-name: windows
            pip-path: ~\AppData\Local\pip\Cache
          - os: macos-latest
            os-name: macos
            pip-path: ~/Library/Caches/pip
          - os: ARM64 # self-hosted linux ARM64 runners
            os-name: linux-arm64
            pip-path: ~/.cache/pip

    name: Build and test on ${{ matrix.os-name }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Python
      if: ${{ matrix.os-name != 'linux-arm64' }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Cache pip packages
      id: pip_cache
      uses: actions/cache@v2
      with:
        path: ${{ matrix.pip-path }}
        key: ${{ matrix.os-name }}-pip

    - name: Install gcc(macos)
      id: gcc_install
      if: ${{ matrix.os-name == 'macos' }}
      run: brew install gcc
  
    - name: Install cmake(linux-arm64)
      id: cmake_install
      if: ${{ matrix.os-name == 'linux-arm64' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Install meson and ninja
      id: meson_install
      run: pip install scikit-build ninja meson

    - name: Meson setup(${{ matrix.os-name }})
      id: meson_setup
      if: ${{ matrix.os-name != 'macos' }}
      run: meson setup builddir/
      env:
        CC: gcc

    - name: Meson setup(macos)
      id: meson_macos_setup
      if: ${{ matrix.os-name == 'macos' }}
      run: meson setup builddir/ -Ddynamic=true
      env:
        CC: gcc

    - name: Meson compile
      run: meson compile -C builddir/ -v

    - name: Meson test
      run: meson test -C builddir/ -v

    - name: Upload Binary
      uses: actions/upload-artifact@v2
      if: ${{ matrix.os-name != 'windows' }}
      with:
        name: binary_${{ matrix.os-name }}
        path: builddir/src/hex-to-image

    - name: Upload Binary(Windows)
      uses: actions/upload-artifact@v2
      if: ${{ matrix.os-name == 'windows' }}
      with:
        name: binary_${{ matrix.os-name }}
        path: builddir/src/hex-to-image.exe

    - name: Upload Test Log
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: meson_testlog_${{ matrix.os-name }}
        path: builddir/meson-logs/testlog.txt

    - name: Upload Output
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: output_${{ matrix.os-name }}
        path: builddir/*.png
