name: meson test

on:
  push:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.h"
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.h
      - ".github/workflows/test.yml"

jobs:

  linux:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install meson and ninja
      run: pip install meson ninja
    - name: setup meson build
      run: meson setup builddir/
      env:
        CC: gcc
    - name: Meson compile
      run: meson compile -C builddir/ -v
    - name: Meson test
      run: meson test -C builddir/ -v
    - name: Upload Log
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: build/meson-logs/testlog.txt

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install gcc
      run: brew install gcc
    - name: Install meson and ninja
      run: pip install meson ninja
    - run: meson setup builddir/
      env:
        CC: gcc
    - name: Meson compile
      run: meson compile -C builddir/ -v
    - name: Meson test
      run: meson test -C builddir/ -v
    - name: Upload Log
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: MacOS_Meson_Testlog
        path: build/meson-logs/testlog.txt

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install meson and ninja
      run: pip install meson ninja
    - run: meson setup builddir/
      env:
        CC: gcc
    - name: Meson compile
      run: meson compile -C builddir/ -v
    - name: Meson test
      run: meson test -C builddir/ -v
    - name: Upload Log
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Windows_Meson_Testlog
        path: build/meson-logs/testlog.txt
